### ISSUE TITLE
Vala package request

### ISSUE THREAD

**Issue by Flat** [nanobox-io/nanobox-pkgsrc-base#1]
From https://wiki.gnome.org/Projects/Vala

> Vala is a new programming language that aims to bring modern programming language features to GNOME developers without imposing any additional runtime requirements and without using a different ABI compared to applications and libraries written in C. 

It would be nice for nanobox to support Vala as it can be difficult to work with on windows machines.

Source code can be found at `https://wiki.gnome.org/Projects/Vala/Release`

**Comment by notxarb** [comment]
A package for vala-0.34.4 has been created
