### ISSUE TITLE
libcairo2 package request

### ISSUE THREAD

**Issue by benspaulding** [nanobox-io/nanobox-pkgsrc-base#12]
Could you please add the libcairo2 package to Nanobox pkgsrc?

https://packages.ubuntu.com/search?keywords=libcairo2

**Comment by notxarb** [comment]
I think the libraries in ubuntu's `libcairo2` package are in the pkgsrc `cairo` package. Can you try using that?

**Comment by benspaulding** [comment]
Oh great, it looks like that will work. Thanks for the help!
