### ISSUE TITLE
AV package requests

### ISSUE THREAD

**Issue by benspaulding** [nanobox-io/nanobox-pkgsrc-base#13]
Could you please add the following packages to Nanobox pkgsrc?

- libavutil-dev
- libavformat-dev
- libavcodec-dev
- libswscale-dev

Thank you!

**Comment by notxarb** [comment]
Those are part of the ffmpeg packages. There's `ffmpeg010`, `ffmpeg1`, `ffmpeg2`, and `ffmpeg3` that you can choose from. It looks like it puts it's header files in a subdirectory in the include folder, so there might be some configuring that needs to happen to look for them in the correct spot. The lib files are also in a subfolder.

**Comment by benspaulding** [comment]
Thanks for the response, @notxarb. I thought that a year or two ago there was a split in the ffmpeg project and some projects stopped using it. Ever since then we have used those I listed directly and it appears that the software we use requires them.

- [ffvideo](https://bitbucket.org/zakhar/ffvideo/wiki/Home)
- [ffvideo setup.py](https://bitbucket.org/zakhar/ffvideo/src/8ab403fc/setup.py?at=default&fileviewer=file-view-default#setup.py-24)

I see the files that you mention in the include and lib directories, but I am not sure how I can configure ffvideo to use them. (Except maybe by forking the project, which I would like to avoid.)

Is there no possibility of getting the individual packages available on the Nanobox pkgsrc?

**Comment by benspaulding** [comment]
I think it is only [libav](https://packages.ubuntu.com/source/trusty/libav) that we need, now that I look.

**Comment by notxarb** [comment]
libav should be available now

**Comment by benspaulding** [comment]
Thanks @notxarb! I see `libav` on pkgsrc now, but I get an error when I try to install it. It seems it cannot get a dependency that it needs, or something. I don’t know how to resolve it.

See my `boxfile.yml` and `nanobox --verbose build` output in [this gist](https://gist.github.com/benspaulding/5bdfe9422be86723ca2b083aeede33d6).

**Comment by notxarb** [comment]
You'll need to run `nanobox update-images` to grab a new `nanobox/build` with a patched `pkgin`

**Comment by benspaulding** [comment]
Thank you!
