### ISSUE TITLE
XML package requests

### ISSUE THREAD

**Issue by benspaulding** [nanobox-io/nanobox-pkgsrc-base#14]
Could you please add the following packages to Nanobox pkgsrc?

- libxml2-dev
- libxslt1-dev

Thanks!

**Comment by danhunsaker** [comment]
Note that `-dev` packages are a Debian/Ubuntu convention to slim down the number of installed files on user systems. In pkgsrc, this distinction is not made, so the files provided by the requested packages in Ubuntu are actually already available in the `xml2` and `xslt` packages.

**Comment by benspaulding** [comment]
Great, `libxml2` and `libxslt` worked. Thank you!
