### ISSUE TITLE
icu-52 and icu-55

### ISSUE THREAD

**Issue by sanderson** [nanobox-io/nanobox-pkgsrc-base#19]
@jayjun is building out a swift engine and needs `icu-52` and `icu-55` packages.

**Comment by jayjun** [comment]
Those packages are the highest available versions for Ubuntu 14.04 and 16.04 respectively, so adding them may indirectly benefit other runtimes too.

**Comment by danhunsaker** [comment]
I'm not against building these, but the version used by our own Swift build will be more important for that use case, when we have one.

**Comment by notxarb** [comment]
Packages for icu-52.1 and icu-55.1nb1 have been uploaded to the package server

**Comment by jayjun** [comment]
Thanks @notxarb! Tested them with official Swift Ubuntu builds, no issues uncovered.
