### ISSUE TITLE
Outdated `zlib` back in images

### ISSUE THREAD

**Issue by danhunsaker** [nanobox-io/nanobox-pkgsrc-base#22]
At one point, we'd released new images with an updated version of `zlib` to resolve the following issue:
```
$ git --version
git: /data/lib/libz.so.1: no version information available (required by git)
git version 2.7.4
```
Older versions were built without version info in the `.so` file itself, and newer systems complain about this because they can't automatically verify that the correct version is being loaded. This unexpected additional output breaks a number of tools expecting _clean_ output, and clutters the display even when things continue to work fine.

So, we need to ensure the latest `zlib` is included in our images, be that by manually installing it once things are up and running, or by updating the bootstrap to use the latest version itself while building.

**Comment by tylerflint** [comment]
As of yesterday, this appears to be fixed. Updating nanobox images will pull in the new bootstrap: `nanobox update-images`
