### ISSUE TITLE
GraphicsMagick 1.3 package request

### ISSUE THREAD

**Issue by laterne** [nanobox-io/nanobox-pkgsrc-base#3]
as an alternative to ImageMagick

**Comment by notxarb** [comment]
GraphicsMagick-1.3.26 should now be available.

**Comment by laterne** [comment]
I added the package in the boxfile:
```
extra_packages:
    - GraphicsMagick
```
the command `gm convert` produces the following error:
`gm: error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory`
