### ISSUE TITLE
Package Request: Opencv-Java

### ISSUE THREAD

**Issue by bnunamak** [nanobox-io/nanobox-pkgsrc-base#32]
Hello,

I need a nanobox build of opencv-java (3.3.0) for my current project. @notxarb was kind enough to build opencv 3.3.0, but I only realized after the fact that it doesn't build the java-relevant files by default.

Instead, there is a "OpenCVDetectApacheAnt.cmake" file included in the CMakeLists of the publicly available sources that detects whether Apache Ant is active or not and builds "/bin/opencv-330.jar" and "/lib/libopencv_java330.so" files if it is. These are the files needed to use opencv in Java.
**Sidenote:** I think cmake also needs to be run with the option "-D BUILD_SHARED_LIBS=OFF".

Unfortunately there isn't a NetBSD package we can just use, but there is an older FreeBSD port that might help: https://svnweb.freebsd.org/ports/head/graphics/opencv-java/

I tried figuring this out myself, but I can't get the vagrant environment to work (@tylerflint had a similar problem) because of an issue with "grub-pc". I have also tried workarounds like building it normally in a linux vagrant environment and hoping it would work, but I ran into a number of missing-dependency / unsatisfied link issues. I also tried using the .jar built on linux with the standard opencv bins and had similar (but different) problems. Building them together is the only way I can see getting it to work.

Some other helpful links:
http://opencv-java-tutorials.readthedocs.io/en/latest/01-installing-opencv-for-java.html#install-opencv-3-x-under-linux
https://github.com/joshuamarquez/docker-opencv-java/blob/master/install.sh

Thanks!

(Moved from https://github.com/nanobox-io/nanobox-pkgsrc-lite)

**Comment by notxarb** [comment]
okay, I finally got opencv compiled again and it should have the jar file with it.
if you have the `opencv` as an `extra_package`, it should install the jar file to `/data/share/OpenCV/java/opencv-331.jar`

**Comment by bnunamak** [comment]
Perfect, it works exactly as expected, thank you!
