### ISSUE TITLE
package request: libssl-dev and libffi-dev

### ISSUE THREAD

**Issue by 01E0E1** [nanobox-io/nanobox-pkgsrc-base#35]
PayPal SDK dependencies.

[https://github.com/paypal/PayPal-Python-SDK#system-requirements](https://github.com/paypal/PayPal-Python-SDK#system-requirements)

**Comment by notxarb** [comment]
Openssl should be installed by default, its headers are in `/data/include`.
Libffi can be found as an `extra_package` named `libffi` and its headers will be in `/data/include`.
