### ISSUE TITLE
Python 3.6 package issues

### ISSUE THREAD

**Issue by benspaulding** [nanobox-io/nanobox-pkgsrc-base#38]
I am unable to get a working Python 3 install on Nanobox. I cannot get all the core packages to install. It seems the core libs (`py36-cElementTree`, `py36-curses`, `py36-expat`, `py36-readline`, `py36-sqlite3`) are not all compiled for the various Python 3 versions. Some are there for some every Python 3.6 build (.0, .1, .2, .3), but not a complete set for a specific version. The engine tells it to install `py36-sqlite3`, but it does not. It completes the build and then errors when I try to use sqlite. If I try to make it install by adding `py36-sqlite3` to `extra_packages` the build fails.

Can all the core Python libraries but compiled for each Python 3 version?

**Comment by notxarb** [comment]
That was probably an issue related to the old pkgsrc, they should be there now. Here is the link to the new repo for reference: http://packages.nanobox.io/2017/11/base/index.html

**Comment by benspaulding** [comment]
Awesome, thanks! Everything seems to be working now.
