### ISSUE TITLE
Package request: xvfb

### ISSUE THREAD

**Issue by Jarmahent** [nanobox-io/nanobox-pkgsrc-base#63]
A virtual frame buffer is required to run the Processing language for Java headless. Which cannot be used unless a virtual frame buffer is running.

Ref: https://github.com/processing/processing/wiki/Running-without-a-Display

**Comment by notxarb** [comment]
Xvfb is part of the modular-xorg-server package
http://packages.nanobox.io/2017/11/base/modular-xorg-server-1.19.5.tgz.html
